export type CommandType =
    // Collection commands
    | "createCollection"
    | "archiveCollection"
    | "publishCollection"
    | "updateCollectionMetadata"
    | "unpublishCollection"
    | "updateCollectionSeoMetadata"
    | "addCollectionImage"
    | "removeCollectionImage"
    | "reorderCollectionImages"
    | "updateCollectionImageAltText"
    | "updateCollectionImage"
    // Bundle commands
    | "createBundle"
    | "archiveBundle"
    | "publishBundle"
    | "unpublishBundle"
    | "updateBundleItems"
    | "updateBundleDetails"
    | "updateBundleMetadata"
    | "updateBundlePrice"
    | "updateBundleCollections"
    | "changeBundleSlug"
    | "updateBundleTaxDetails"
    | "addBundleImage"
    | "removeBundleImage"
    | "reorderBundleImages"
    | "updateBundleImageAltText"
    // Digital Downloadable Product commands
    | "createDigitalDownloadableProduct"
    | "archiveDigitalDownloadableProduct"
    | "publishDigitalDownloadableProduct"
    | "unpublishDigitalDownloadableProduct"
    | "changeDigitalDownloadableProductSlug"
    | "updateDigitalDownloadableProductDetails"
    | "updateDigitalDownloadableProductMetadata"
    | "updateDigitalDownloadableProductClassification"
    | "updateDigitalDownloadableProductTags"
    | "updateDigitalDownloadableProductCollections"
    | "updateDigitalDownloadableProductOptions"
    | "updateDigitalDownloadableProductTaxDetails"
    | "setDigitalDownloadableProductDefaultVariant"
    | "updateDigitalDownloadableProductDownloadSettings"
    | "scheduleDigitalDownloadableProductDrop"
    | "updateScheduledDigitalDownloadableProductDrop"
    | "cancelScheduledDigitalDownloadableProductDrop"
    // Digital Downloadable Variant commands
    | "createDigitalDownloadableVariant"
    | "archiveDigitalDownloadableVariant"
    | "publishDigitalDownloadableVariant"
    | "updateDigitalDownloadableVariantDetails"
    | "updateDigitalDownloadableVariantPrice"
    | "updateDigitalDownloadableVariantSku"
    | "addDigitalDownloadableVariantImage"
    | "removeDigitalDownloadableVariantImage"
    | "reorderDigitalDownloadableVariantImages"
    | "updateDigitalDownloadableVariantImageAltText"
    | "attachDigitalDownloadableVariantDigitalAsset"
    | "detachDigitalDownloadableVariantDigitalAsset"
    | "updateDigitalDownloadableVariantDownloadSettings"
    | "scheduleDigitalDownloadableVariantDrop"
    | "updateScheduledDigitalDownloadableVariantDrop"
    | "cancelScheduledDigitalDownloadableVariantDrop"
    | "updateDigitalDownloadableVariantSale"
    | "scheduleDigitalDownloadableVariantSale"
    | "updateScheduledDigitalDownloadableVariantSale"
    | "cancelScheduledDigitalDownloadableVariantSale"
    // Dropship Product commands
    | "createDropshipProduct"
    | "archiveDropshipProduct"
    | "publishDropshipProduct"
    | "unpublishDropshipProduct"
    | "changeDropshipProductSlug"
    | "updateDropshipProductDetails"
    | "updateDropshipProductMetadata"
    | "updateDropshipProductClassification"
    | "updateDropshipProductTags"
    | "updateDropshipProductCollections"
    | "updateDropshipProductOptions"
    | "updateDropshipProductTaxDetails"
    | "setDropshipProductDefaultVariant"
    | "updateDropshipProductSafetyBuffer"
    | "updateDropshipProductFulfillmentSettings"
    | "scheduleDropshipProductDrop"
    | "updateScheduledDropshipProductDrop"
    | "cancelScheduledDropshipProductDrop"
    // Dropship Variant commands
    | "createDropshipVariant"
    | "archiveDropshipVariant"
    | "publishDropshipVariant"
    | "updateDropshipVariantDetails"
    | "updateDropshipVariantPrice"
    | "updateDropshipVariantSku"
    | "addDropshipVariantImage"
    | "removeDropshipVariantImage"
    | "reorderDropshipVariantImages"
    | "updateDropshipVariantImageAltText"
    | "updateDropshipVariantInventory"
    | "updateDropshipVariantFulfillmentSettings"
    | "scheduleDropshipVariantDrop"
    | "updateScheduledDropshipVariantDrop"
    | "cancelScheduledDropshipVariantDrop"
    | "updateDropshipVariantSale"
    | "scheduleDropshipVariantSale"
    | "updateScheduledDropshipVariantSale"
    | "cancelScheduledDropshipVariantSale";

export abstract class Command {
    abstract id: string;
    abstract userId: string;
    abstract type: CommandType;
    correlationId?: string;
}
