export const schemas = [
  `CREATE TABLE IF NOT EXISTS events (
    eventType TEXT NOT NULL,
    version INTEGER NOT NULL,
    aggregateId TEXT NOT NULL,
    correlationId TEXT NOT NULL,
    occurredAt TEXT NOT NULL,
    userId TEXT NOT NULL,
    payload TEXT NOT NULL,
    PRIMARY KEY (aggregateId, version)
  )`,
  `CREATE TABLE IF NOT EXISTS snapshots (
    aggregateId TEXT PRIMARY KEY,
    correlationId TEXT NOT NULL,
    version INTEGER NOT NULL,
    payload TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS outbox (
    id TEXT PRIMARY KEY,
    aggregateId TEXT NOT NULL,
    eventType TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    retryCount INTEGER NOT NULL DEFAULT 0,
    lastAttemptAt TEXT,
    nextRetryAt TEXT,
    idempotencyKey TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS outboxProcessing (
    id TEXT PRIMARY KEY,
    outboxId TEXT NOT NULL,
    handlerId TEXT NOT NULL,
    idempotencyKey TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending',
    retryCount INTEGER NOT NULL DEFAULT 0,
    lastAttemptAt TEXT,
    nextRetryAt TEXT,
    processedAt TEXT,
    FOREIGN KEY (outboxId) REFERENCES outbox(id)
  )`,
  `CREATE TABLE IF NOT EXISTS outboxDlq (
    id TEXT PRIMARY KEY,
    outboxId TEXT NOT NULL,
    handlerId TEXT NOT NULL,
    eventType TEXT NOT NULL,
    payload TEXT NOT NULL,
    errorMessage TEXT,
    finalRetryCount INTEGER NOT NULL,
    failedAt TEXT NOT NULL,
    originalOccurredAt TEXT,
    FOREIGN KEY (outboxId) REFERENCES outbox(id)
  )`,
  `CREATE TABLE IF NOT EXISTS productReadModel (
    aggregateId TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    vendor TEXT NOT NULL,
    description TEXT NOT NULL,
    tags TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    correlationId TEXT NOT NULL,
    taxable INTEGER NOT NULL DEFAULT 1,
    taxId TEXT NOT NULL DEFAULT '',
    productType TEXT NOT NULL,
    dropshipSafetyBuffer INTEGER,
    fulfillmentProviderId TEXT,
    supplierCost REAL,
    supplierSku TEXT,
    maxDownloads INTEGER,
    accessDurationDays INTEGER,
    variantOptions TEXT NOT NULL DEFAULT '[]',
    version INTEGER NOT NULL,
    updatedAt TEXT NOT NULL,
    publishedAt TEXT,
    collections TEXT NOT NULL,
    metaTitle TEXT NOT NULL DEFAULT '',
    metaDescription TEXT NOT NULL DEFAULT '',
    richDescriptionUrl TEXT NOT NULL DEFAULT '',
    defaultVariantId TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_productReadModel_status ON productReadModel(status)`,
  `CREATE TABLE IF NOT EXISTS collectionProductsReadModel (
    collectionId TEXT NOT NULL,
    productId TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    vendor TEXT NOT NULL,
    description TEXT NOT NULL,
    tags TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    taxable INTEGER NOT NULL DEFAULT 1,
    taxId TEXT NOT NULL DEFAULT '',
    productType TEXT NOT NULL,
    dropshipSafetyBuffer INTEGER,
    fulfillmentProviderId TEXT,
    supplierCost REAL,
    supplierSku TEXT,
    maxDownloads INTEGER,
    accessDurationDays INTEGER,
    variantOptions TEXT NOT NULL DEFAULT '[]',
    metaTitle TEXT NOT NULL DEFAULT '',
    metaDescription TEXT NOT NULL DEFAULT '',
    richDescriptionUrl TEXT NOT NULL DEFAULT '',
    variantIds TEXT NOT NULL DEFAULT '[]',
    productCreatedAt TEXT NOT NULL,
    productUpdatedAt TEXT NOT NULL,
    publishedAt TEXT,
    correlationId TEXT NOT NULL,
    productVersion INTEGER NOT NULL,
    PRIMARY KEY (collectionId, productId)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_collectionProducts_collectionId ON collectionProductsReadModel(collectionId)`,
  `CREATE INDEX IF NOT EXISTS idx_collectionProducts_productId ON collectionProductsReadModel(productId)`,
  `CREATE INDEX IF NOT EXISTS idx_collectionProducts_position ON collectionProductsReadModel(collectionId, position)`,
  `CREATE INDEX IF NOT EXISTS idx_collectionProducts_status ON collectionProductsReadModel(status)`,
  `CREATE TABLE IF NOT EXISTS collectionsReadModel (
    aggregateId TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    correlationId TEXT NOT NULL,
    version INTEGER NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    metaTitle TEXT NOT NULL DEFAULT '',
    metaDescription TEXT NOT NULL DEFAULT '',
    publishedAt TEXT,
    images TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_collectionsReadModel_status ON collectionsReadModel(status)`,
  `CREATE TABLE IF NOT EXISTS slugRedirects (
    oldSlug TEXT PRIMARY KEY,
    newSlug TEXT NOT NULL,
    aggregateId TEXT NOT NULL,
    aggregateType TEXT NOT NULL,
    productId TEXT,
    createdAt TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_slugRedirects_newSlug ON slugRedirects(newSlug)`,
  `CREATE INDEX IF NOT EXISTS idx_slugRedirects_aggregate ON slugRedirects(aggregateId, aggregateType)`,
  // Better Auth tables - kept as-is per requirements
  `CREATE TABLE IF NOT EXISTS user (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    emailVerified INTEGER NOT NULL,
    image TEXT,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS session (
    id TEXT NOT NULL PRIMARY KEY,
    expiresAt TEXT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    ipAddress TEXT,
    userAgent TEXT,
    userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS account (
    id TEXT NOT NULL PRIMARY KEY,
    accountId TEXT NOT NULL,
    providerId TEXT NOT NULL,
    userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    accessToken TEXT,
    refreshToken TEXT,
    idToken TEXT,
    accessTokenExpiresAt TEXT,
    refreshTokenExpiresAt TEXT,
    scope TEXT,
    password TEXT,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS verification (
    id TEXT NOT NULL PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    expiresAt TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS schedulesReadModel (
    aggregateId TEXT PRIMARY KEY,
    targetAggregateId TEXT NOT NULL,
    targetAggregateType TEXT NOT NULL,
    commandType TEXT NOT NULL,
    commandData TEXT,
    scheduledFor TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    retryCount INTEGER NOT NULL DEFAULT 0,
    nextRetryAt TEXT,
    createdBy TEXT NOT NULL,
    errorMessage TEXT,
    correlationId TEXT NOT NULL,
    version INTEGER NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_schedulesReadModel_status ON schedulesReadModel(status)`,
  `CREATE INDEX IF NOT EXISTS idx_schedulesReadModel_scheduledFor ON schedulesReadModel(scheduledFor)`,
  `CREATE INDEX IF NOT EXISTS idx_schedulesReadModel_status_scheduledFor ON schedulesReadModel(status, scheduledFor)`,
  `CREATE INDEX IF NOT EXISTS idx_schedulesReadModel_targetAggregate ON schedulesReadModel(targetAggregateId)`,
  `CREATE TABLE IF NOT EXISTS variantReadModel (
    aggregateId TEXT PRIMARY KEY,
    productId TEXT NOT NULL,
    sku TEXT NOT NULL,
    price REAL NOT NULL,
    inventory INTEGER NOT NULL,
    options TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    correlationId TEXT NOT NULL,
    version INTEGER NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    publishedAt TEXT,
    images TEXT NOT NULL,
    digitalAsset TEXT,
    fulfillmentProviderId TEXT,
    supplierCost REAL,
    supplierSku TEXT,
    maxDownloads INTEGER,
    accessDurationDays INTEGER
  )`,
  `CREATE INDEX IF NOT EXISTS idx_variantReadModel_productId ON variantReadModel(productId)`,
  `CREATE INDEX IF NOT EXISTS idx_variantReadModel_status ON variantReadModel(status)`,
  `CREATE INDEX IF NOT EXISTS idx_variantReadModel_sku ON variantReadModel(sku)`,
  `CREATE TABLE IF NOT EXISTS productVariantsReadModel (
    productId TEXT NOT NULL,
    variantId TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    -- Variant fields
    sku TEXT NOT NULL,
    price REAL NOT NULL,
    inventory INTEGER NOT NULL,
    options TEXT NOT NULL,
    variantStatus TEXT NOT NULL DEFAULT 'draft',
    images TEXT NOT NULL,
    digitalAsset TEXT,
    variantFulfillmentProviderId TEXT,
    variantSupplierCost REAL,
    variantSupplierSku TEXT,
    variantMaxDownloads INTEGER,
    variantAccessDurationDays INTEGER,
    variantCreatedAt TEXT NOT NULL,
    variantUpdatedAt TEXT NOT NULL,
    variantPublishedAt TEXT,
    -- Product fields (full denormalization)
    productName TEXT NOT NULL,
    productSlug TEXT NOT NULL,
    productDescription TEXT NOT NULL,
    productStatus TEXT NOT NULL DEFAULT 'draft',
    productVendor TEXT NOT NULL,
    productType TEXT NOT NULL,
    dropshipSafetyBuffer INTEGER,
    fulfillmentProviderId TEXT,
    supplierCost REAL,
    supplierSku TEXT,
    maxDownloads INTEGER,
    accessDurationDays INTEGER,
    defaultVariantId TEXT,
    variantOptions TEXT NOT NULL DEFAULT '[]',
    collections TEXT NOT NULL DEFAULT '[]',
    tags TEXT NOT NULL DEFAULT '[]',
    taxable INTEGER NOT NULL DEFAULT 1,
    taxId TEXT NOT NULL DEFAULT '',
    metaTitle TEXT NOT NULL DEFAULT '',
    metaDescription TEXT NOT NULL DEFAULT '',
    richDescriptionUrl TEXT NOT NULL DEFAULT '',
    productCreatedAt TEXT NOT NULL,
    productUpdatedAt TEXT NOT NULL,
    productPublishedAt TEXT,
    -- Tracking
    variantCorrelationId TEXT NOT NULL,
    variantVersion INTEGER NOT NULL,
    PRIMARY KEY (productId, variantId)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_productId ON productVariantsReadModel(productId)`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_variantId ON productVariantsReadModel(variantId)`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_position ON productVariantsReadModel(productId, position)`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_sku ON productVariantsReadModel(sku)`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_variantStatus ON productVariantsReadModel(variantStatus)`,
  `CREATE INDEX IF NOT EXISTS idx_productVariants_productStatus ON productVariantsReadModel(productStatus)`,
  `CREATE TABLE IF NOT EXISTS bundleReadModel (
    aggregateId TEXT PRIMARY KEY,
    correlationId TEXT NOT NULL,
    version INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    slug TEXT NOT NULL,
    items TEXT NOT NULL DEFAULT '[]',
    price REAL NOT NULL DEFAULT 0,
    compareAtPrice REAL,
    metaTitle TEXT NOT NULL DEFAULT '',
    metaDescription TEXT NOT NULL DEFAULT '',
    richDescriptionUrl TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '[]',
    collections TEXT NOT NULL DEFAULT '[]',
    images TEXT NOT NULL DEFAULT '[]',
    taxable INTEGER NOT NULL DEFAULT 1,
    taxId TEXT NOT NULL DEFAULT '',
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    publishedAt TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_bundleReadModel_status ON bundleReadModel(status)`,
  `CREATE INDEX IF NOT EXISTS idx_bundleReadModel_slug ON bundleReadModel(slug)`,
];
